[package]
name = "algebraeon"
version = "0.0.12"
edition = "2024"
license = "GPL-3.0-only"
description = "Algebraeon computational algebra library re-exports for all components"
repository = "https://github.com/pishleback/Algebraeon"
keywords = ["maths", "matrix", "polynomial", "number-theory", "factoring"]
categories = ["mathematics"]
readme = "../README.md"

[lib]
name = "algebraeon"

[dependencies]
algebraeon-sets = { version = "=0.0.12", path = "../sets" }
algebraeon-nzq = { version = "=0.0.12", path = "../nzq" }
algebraeon-groups = { version = "=0.0.12", path = "../groups" }
algebraeon-rings = { version = "=0.0.12", path = "../rings"}
algebraeon-geometry = { version = "=0.0.12", path = "../geometry" }

[features]
default = ["conway-polynomials-buildtime-fetch"]
conway-polynomials-buildtime-fetch = ["algebraeon-rings/conway-polynomials-buildtime-fetch"]
conway-polynomials-runtime-fetch = ["algebraeon-rings/conway-polynomials-runtime-fetch"]