[package]
name = "algebraeon"
version = "0.1.2"
edition = "2024"
license = "GPL-3.0-only"
description = "Algebraeon computational algebra library re-exports for all components"
repository = "https://github.com/pishleback/Algebraeon"
keywords = ["maths", "matrix", "polynomial", "number-theory", "factoring"]
categories = ["mathematics"]
readme = "../README.md"

[lib]
name = "algebraeon"

[dependencies]
algebraeon-sets = { version = "0.1.2", path = "../sets" }
algebraeon-nzq = { version = "0.1.2", path = "../nzq" }
algebraeon-groups = { version = "0.1.2", path = "../groups" }
algebraeon-rings = { version = "0.1.2", path = "../rings" }
algebraeon-geometry = { version = "0.1.2", path = "../geometry" }
