[workspace]
resolver = "2"
members = [
    "sets",
    "nzq",
    "groups",
    "rings",
    "geometry",
    "drawing",
    "combinatorics",
    "examples", 
    "algebraeon",
]

# To publish
# Update CHANGELOG
# Check all ok:
#   cargo ws publish --no-individual-tags --dry-run
# Publish
#   cargo ws publish --no-individual-tags
