[package]
name = "orthoclase-package"
version = "0.1.0"
edition = "2021"

[lib]
name = "orthoclase_all"
path = "src/lib.rs"

[[bin]]
name = "main"
doc = false

[[bin]]
name = "main_sc"
doc = false

[dependencies]
rayon="1.7.0"
itertools="0.11.0"
malachite-base = "0.3.2"
malachite-nz = "0.3.2"
malachite-q = "0.3.2"
glium = "0.32"
rand = "0.8.5"
static_assertions = "1.1.0"
derivative = "2.2.0"