[workspace]
resolver = "2"
members = [
    "sets",
    "nzq",
    "groups",
    "rings",
    "geometry",
    "drawing",
    "combinatorics",
    "examples", 
    "algebraeon",
]

# https://github.com/pksunkara/cargo-workspaces
# To publish
# Update CHANGELOG
# Check all ok:
#   cargo ws publish --no-individual-tags --from-git --dry-run
# Bump versions
#   cargo ws version --no-individual-tags
# Publish
#   cargo ws publish --no-individual-tags --from-git
