[workspace]
resolver = "2"
members = [
    "sets",
    "nzq",
    "groups",
    "rings",
    "geometry",
    "drawing",
    "combinatorics",
    "examples", 
    "algebraeon",
]

# To publish
# cargo ws publish --no-individual-tags
