[package]
name = "algebraeon-groups"
version = "0.0.8"
edition = "2021"
license = "GPL-3.0-only"
description = "Algorithms in group theory."
repository = "https://github.com/pishleback/Algebraeon"
keywords = ["maths", "groups", "permutations"]
categories = ["mathematics"]
readme = "../README.md"

[lib]
name = "algebraeon_groups"

[dependencies]
itertools="0.11.0"
rayon="1.7.0"
malachite-base = "0.3.2"
malachite-nz = "0.3.2"
malachite-q = "0.3.2"
