[package]
name = "algebraeon-sets"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-only"
description = "Algorithms in combinatorics."
repository = "https://github.com/pishleback/Algebraeon"
keywords = ["maths", "combinatorics"]
categories = ["mathematics"]

[lib]
name = "algebraeon_sets"

[dependencies]
malachite-base = "0.3.2"
malachite-nz = "0.3.2"
malachite-q = "0.3.2"
