[package]
name = "algebraeon-sets"
version = "0.1.7"
edition = "2024"
license = "GPL-3.0-only"
description = "Algorithms in combinatorics."
repository = "https://github.com/pishleback/Algebraeon"
keywords = ["maths", "combinatorics"]
categories = ["mathematics"]
readme = "../README.md"

[lib]
name = "algebraeon_sets"

[dependencies]
malachite-base = "0.5.1"
