[package]
name = "algebraeon-sets"
version = "0.1.5"
edition = "2024"
license = "GPL-3.0-only"
description = "Algorithms in combinatorics."
repository = "https://github.com/pishleback/Algebraeon"
keywords = ["maths", "combinatorics"]
categories = ["mathematics"]
readme = "../README.md"

[lib]
name = "algebraeon_sets"
