[package]
name = "algebraeon-rings"
version = "0.1.0"
edition = "2021"

[lib]
name = "algebraeon_rings"

[dependencies]
algebraeon-sets = { version = "0.1.0", path = "../sets" }
algebraeon-groups = { version = "0.1.0", path = "../groups" }
rand = "0.8.5"
rayon="1.7.0"
itertools="0.11.0"
malachite-base = "0.3.2"
malachite-nz = "0.3.2"
malachite-q = "0.3.2"