name: Cargo run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt install libfontconfig1-dev

    - name: Run tests in debug
      run: cargo test --verbose

  build_and_test_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt install libfontconfig1-dev

    - name: Run tests
      run: cargo test --release --verbose
